# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ButtonParameterTypeEnum(object):

    """Implementation of the 'ButtonParameterType' enum.

    TODO: type enum description here.

    Attributes:
        PAYLOAD: TODO: type description here.
        TEXT: TODO: type description here.

    """

    PAYLOAD = 'payload'

    TEXT = 'text'
