# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ComponentTypeEnum(object):

    """Implementation of the 'ComponentType' enum.

    TODO: type enum description here.

    Attributes:
        HEADER: TODO: type description here.
        BODY: TODO: type description here.
        BUTTON: TODO: type description here.

    """

    HEADER = 'header'

    BODY = 'body'

    BUTTON = 'button'
