# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Currency(object):

    """Implementation of the 'Currency' model.

    TODO: type model description here.

    Attributes:
        fallback_value (string): Default text if localization fails.
        code (string): Currency code as defined in ISO 4217.
        amount_1000 (int): Amount multiplied by 1000.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fallback_value": 'fallback_value',
        "code": 'code',
        "amount_1000": 'amount_1000'
    }

    def __init__(self,
                 fallback_value=None,
                 code=None,
                 amount_1000=None):
        """Constructor for the Currency class"""

        # Initialize members of the class
        self.fallback_value = fallback_value 
        self.code = code 
        self.amount_1000 = amount_1000 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        fallback_value = dictionary.get("fallback_value") if dictionary.get("fallback_value") else None
        code = dictionary.get("code") if dictionary.get("code") else None
        amount_1000 = dictionary.get("amount_1000") if dictionary.get("amount_1000") else None
        # Return an object of this model
        return cls(fallback_value,
                   code,
                   amount_1000)
