# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Footer(object):

    """Implementation of the 'Footer' model.

    TODO: type model description here.

    Attributes:
        text (string): The footer content. Emojis and markdown are supported.
            Links are supported.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "text": 'text'
    }

    def __init__(self,
                 text=None):
        """Constructor for the Footer class"""

        # Initialize members of the class
        self.text = text 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        text = dictionary.get("text") if dictionary.get("text") else None
        # Return an object of this model
        return cls(text)
