# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class HeaderTypeEnum(object):

    """Implementation of the 'HeaderType' enum.

    TODO: type enum description here.

    Attributes:
        TEXT: Used for List Messages and Reply Buttons.
        DOCUMENT: Used for Reply Buttons.
        IMAGE: Used for Reply Buttons.
        VIDEO: Used for Reply Buttons.

    """

    TEXT = 'text'

    DOCUMENT = 'document'

    IMAGE = 'image'

    VIDEO = 'video'
