# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InteractiveTypeEnum(object):

    """Implementation of the 'InteractiveType' enum.

    The type of interactive message you want to send.

    Attributes:
        LIST: TODO: type description here.
        BUTTON: TODO: type description here.

    """

    LIST = 'list'

    BUTTON = 'button'
