# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MessageTypeEnum(object):

    """Implementation of the 'MessageType' enum.

    TODO: type enum description here.

    Attributes:
        TEXT: TODO: type description here.
        AUDIO: TODO: type description here.
        CONTACTS: TODO: type description here.
        DOCUMENT: TODO: type description here.
        IMAGE: TODO: type description here.
        INTERACTIVE: TODO: type description here.
        LOCATION: TODO: type description here.
        STICKER: TODO: type description here.
        TEMPLATE: TODO: type description here.
        VIDEO: TODO: type description here.

    """

    TEXT = 'text'

    AUDIO = 'audio'

    CONTACTS = 'contacts'

    DOCUMENT = 'document'

    IMAGE = 'image'

    INTERACTIVE = 'interactive'

    LOCATION = 'location'

    STICKER = 'sticker'

    TEMPLATE = 'template'

    VIDEO = 'video'
