# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from whatsappcloudapi.api_helper import APIHelper


class Org(object):

    """Implementation of the 'Org' model.

    TODO: type model description here.

    Attributes:
        company (string): Name of the contact's company.
        department (string): Name of the contact's department.
        title (string): Contact's business title.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "company": 'company',
        "department": 'department',
        "title": 'title'
    }

    _optionals = [
        'company',
        'department',
        'title',
    ]

    def __init__(self,
                 company=APIHelper.SKIP,
                 department=APIHelper.SKIP,
                 title=APIHelper.SKIP):
        """Constructor for the Org class"""

        # Initialize members of the class
        if company is not APIHelper.SKIP:
            self.company = company 
        if department is not APIHelper.SKIP:
            self.department = department 
        if title is not APIHelper.SKIP:
            self.title = title 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        company = dictionary.get("company") if dictionary.get("company") else APIHelper.SKIP
        department = dictionary.get("department") if dictionary.get("department") else APIHelper.SKIP
        title = dictionary.get("title") if dictionary.get("title") else APIHelper.SKIP
        # Return an object of this model
        return cls(company,
                   department,
                   title)
