# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ParameterTypeEnum(object):

    """Implementation of the 'ParameterType' enum.

    TODO: type enum description here.

    Attributes:
        TEXT: TODO: type description here.
        CURRENCY: TODO: type description here.
        DATE_TIME: TODO: type description here.
        IMAGE: TODO: type description here.
        DOCUMENT: TODO: type description here.
        VIDEO: TODO: type description here.

    """

    TEXT = 'text'

    CURRENCY = 'currency'

    DATE_TIME = 'date_time'

    IMAGE = 'image'

    DOCUMENT = 'document'

    VIDEO = 'video'
