# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PersonalInformationTypeEnum(object):

    """Implementation of the 'PersonalInformationType' enum.

    TODO: type enum description here.

    Attributes:
        HOME: TODO: type description here.
        WORK: TODO: type description here.

    """

    HOME = 'HOME'

    WORK = 'WORK'
