# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PhoneTypeEnum(object):

    """Implementation of the 'PhoneType' enum.

    TODO: type enum description here.

    Attributes:
        HOME: TODO: type description here.
        WORK: TODO: type description here.
        CELL: TODO: type description here.
        MAIN: TODO: type description here.
        IPHONE: TODO: type description here.

    """

    HOME = 'HOME'

    WORK = 'WORK'

    CELL = 'CELL'

    MAIN = 'MAIN'

    IPHONE = 'IPHONE'
