# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class QualityRatingEnum(object):

    """Implementation of the 'QualityRating' enum.

    For more information relating to quality rating, see [About WhatsApp
    Business Account Message Quality
    Rating](https://www.facebook.com/business/help/896873687365001).

    Attributes:
        GREEN: High Quality.
        YELLOW: Medium Quality.
        RED: Low Quality.
        NA: Quality has not been determined.

    """

    GREEN = 'GREEN'

    YELLOW = 'YELLOW'

    RED = 'RED'

    NA = 'NA'
