# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RegisterPhoneRequest(object):

    """Implementation of the 'RegisterPhoneRequest' model.

    TODO: type model description here.

    Attributes:
        messaging_product (string): Messaging service used. In this case, use
            "whatsapp".
        pin (string): A 6-digit pin you have previously set up - See Set
            Two-Step Verification.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "messaging_product": 'messaging_product',
        "pin": 'pin'
    }

    def __init__(self,
                 messaging_product=None,
                 pin=None):
        """Constructor for the RegisterPhoneRequest class"""

        # Initialize members of the class
        self.messaging_product = messaging_product 
        self.pin = pin 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        messaging_product = dictionary.get("messaging_product") if dictionary.get("messaging_product") else None
        pin = dictionary.get("pin") if dictionary.get("pin") else None
        # Return an object of this model
        return cls(messaging_product,
                   pin)
