# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RequestVerificationCodeMethodEnum(object):

    """Implementation of the 'RequestVerificationCodeMethod' enum.

    TODO: type enum description here.

    Attributes:
        SMS: TODO: type description here.
        VOICE: TODO: type description here.

    """

    SMS = 'SMS'

    VOICE = 'VOICE'
