# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResponseContact(object):

    """Implementation of the 'ResponseContact' model.

    TODO: type model description here.

    Attributes:
        input (string): TODO: type description here.
        wa_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "input": 'input',
        "wa_id": 'wa_id'
    }

    def __init__(self,
                 input=None,
                 wa_id=None):
        """Constructor for the ResponseContact class"""

        # Initialize members of the class
        self.input = input 
        self.wa_id = wa_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        input = dictionary.get("input") if dictionary.get("input") else None
        wa_id = dictionary.get("wa_id") if dictionary.get("wa_id") else None
        # Return an object of this model
        return cls(input,
                   wa_id)
