# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from whatsappcloudapi.api_helper import APIHelper


class Row(object):

    """Implementation of the 'Row' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        title (string): TODO: type description here.
        description (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "title": 'title',
        "description": 'description'
    }

    _optionals = [
        'description',
    ]

    def __init__(self,
                 id=None,
                 title=None,
                 description=APIHelper.SKIP):
        """Constructor for the Row class"""

        # Initialize members of the class
        self.id = id 
        self.title = title 
        if description is not APIHelper.SKIP:
            self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else None
        title = dictionary.get("title") if dictionary.get("title") else None
        description = dictionary.get("description") if dictionary.get("description") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   title,
                   description)
