# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SetTwoStepVerificationCodeRequest(object):

    """Implementation of the 'SetTwoStepVerificationCodeRequest' model.

    A 6-digit pin you wish to use for two-step authentication.

    Attributes:
        pin (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pin": 'pin'
    }

    def __init__(self,
                 pin=None):
        """Constructor for the SetTwoStepVerificationCodeRequest class"""

        # Initialize members of the class
        self.pin = pin 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        pin = dictionary.get("pin") if dictionary.get("pin") else None
        # Return an object of this model
        return cls(pin)
