# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubTypeEnum(object):

    """Implementation of the 'SubType' enum.

    TODO: type enum description here.

    Attributes:
        QUICKREPLY: Refers to a previously created quick reply button that
            allows for the customer to return a predefined message.
        URL: Refers to a previously created button that allows the customer to
            visit the URL generated by appending the text parameter to the
            predefined prefix URL in the template.

    """

    QUICKREPLY = 'quick_reply'

    URL = 'url'
