# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class VerticalEnum(object):

    """Implementation of the 'Vertical' enum.

    TODO: type enum description here.

    Attributes:
        UNDEFINED: TODO: type description here.
        OTHER: TODO: type description here.
        AUTO: TODO: type description here.
        BEAUTY: TODO: type description here.
        APPAREL: TODO: type description here.
        EDU: TODO: type description here.
        ENTERTAIN: TODO: type description here.
        EVENT_PLAN: TODO: type description here.
        FINANCE: TODO: type description here.
        GROCERY: TODO: type description here.
        GOVT: TODO: type description here.
        HOTEL: TODO: type description here.
        HEALTH: TODO: type description here.
        NONPROFIT: TODO: type description here.
        PROF_SERVICES: TODO: type description here.
        RETAIL: TODO: type description here.
        TRAVEL: TODO: type description here.
        RESTAURANT: TODO: type description here.
        NOT_A_BIZ: TODO: type description here.

    """

    UNDEFINED = 'UNDEFINED'

    OTHER = 'OTHER'

    AUTO = 'AUTO'

    BEAUTY = 'BEAUTY'

    APPAREL = 'APPAREL'

    EDU = 'EDU'

    ENTERTAIN = 'ENTERTAIN'

    EVENT_PLAN = 'EVENT_PLAN'

    FINANCE = 'FINANCE'

    GROCERY = 'GROCERY'

    GOVT = 'GOVT'

    HOTEL = 'HOTEL'

    HEALTH = 'HEALTH'

    NONPROFIT = 'NONPROFIT'

    PROF_SERVICES = 'PROF_SERVICES'

    RETAIL = 'RETAIL'

    TRAVEL = 'TRAVEL'

    RESTAURANT = 'RESTAURANT'

    NOT_A_BIZ = 'NOT_A_BIZ'
